version: "3.8"

services:
  php-apache-environment:
    build:
      dockerfile: Dockerfile
    depends_on:
      - easyroomhost
    volumes:
      - ./booker:/var/www/html/
    ports:
      - "8080:80"
    networks:
      - my-network # เพิ่มบรรทัดนี้

  easyroomhost:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234" # รหัสผ่านสำหรับ root
      MYSQL_DATABASE: easyroom # ชื่อฐานข้อมูลเริ่มต้น
      MYSQL_USER: easyroomteam
      MYSQL_PASSWORD: "1234" # รหัสผ่านสำหรับ user
    ports:
      - "9906:3306"
    volumes:
      - db_data:/var/lib/mysql # เก็บข้อมูลฐานข้อมูล
      - ./easyroom.sql:/docker-entrypoint-initdb.d/easyroom.sql # ใส่ไฟล์ SQL สำหรับ initialize database
      - ./mysql-init:/docker-entrypoint-initdb.d # โฟลเดอร์ที่ใช้เก็บไฟล์ SQL หรือ script อื่นๆ
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: easyroomhost
      PMA_USER: root
      PMA_PASSWORD: "1234"
    depends_on:
      - easyroomhost
    networks:
      - my-network

volumes:
  db_data:
    driver: local

networks:
  my-network:
    driver: bridge
